update Notify to exports.qbx_core.Notify
Qbox-project/qbx_prison pull request #24
Opened 2024-02-15 04:50 UTC by bicatcho11

## Description

update Notify to exports.qbx_core.Notify

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My pull request fits the contribution guidelines & code conventions.

2024-02-17 18:13 UTC, Manason approved these changes

2024-02-17 18:13 UTC, Manason commented on server/main.lua
> +            exports.qbx_core.Notify(src, locale("info.lost_job"))
```suggestion
            exports.qbx_core:Notify(src, locale("info.lost_job"))
```

2024-02-17 18:13 UTC, Manason commented on server/main.lua
> +    exports.qbx_core.Notify(src, locale('success.found_item', Config.Jobs.electrician.reward), 'success')
```suggestion
    exports.qbx_core:Notify(src, locale('success.found_item', Config.Jobs.electrician.reward), 'success')
```

2024-02-18 07:34 UTC, Manason approved these changes

2024-02-18 09:25 UTC, solareon requested changes
If we are adding locale strings please add them to all the locales to prevent issues.

2024-02-19 12:08 UTC, BerkieBb approved these changes

2024-02-19 12:08 UTC, BerkieBb commented on client/prisonbreak.lua
> +                    qbx.drawText3d({ text = "~r~" .. locale('info.system_lockdown'), coords = gates[i].coords })
This ~r~ can be added to the locales as well

2024-02-24 17:18 UTC, merged

2024-02-24 17:19 UTC, solareon approved these changes

2024-02-24 17:19 UTC, solareon commented on locales/ar.json
> +    "found_item": "لقد وجدت %s..",
nice catch