Adding a condition for smuggling prisoners
Qbox-project/qbx_prison pull request #30
Opened 2024-02-24 08:13 UTC by bicatcho11

## Description

Adding a condition for smuggling prisoners

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My pull request fits the contribution guidelines & code conventions.

2024-02-24 17:36 UTC, Manason requested changes
Can you describe this feature in greater detail? I see that the code has enabled police to also break into prison given a certain total number of police are active. Is that the intention?

2024-02-24 19:25 UTC, bicatcho11 commented
> Can you describe this feature in greater detail? I see that the code has enabled police to also break into prison given a certain total number of police are active. Is that the intention?

I mean he can't start the hack without a certain number of police

2024-02-25 11:38 UTC, BerkieBb requested changes

2024-02-25 11:38 UTC, BerkieBb commented on client/prisonbreak.lua
> +    if QBX.PlayerData.job.type == 'leo' and QBX.PlayerData.job.onduty < Config.minPolice then
This code doesn't make sense.
First of all, you're comparing a boolean to a number.
Second of all, this code is client side and only checking one person, this should be server side with a callback.

2024-02-25 17:48 UTC, closed without merging