add jailalarm command
Qbox-project/qbx_prison pull request #36
Opened 2024-03-28 23:14 UTC by bicatcho11

## Description

add jailalarm command

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My pull request fits the contribution guidelines & code conventions.

2024-03-28 23:16 UTC, bicatcho11 commented
https://github.com/Qbox-project/qbx_policejob/pull/96

2024-03-31 17:03 UTC, mafewtm commented
I'd look at the documentation for the `GetDutyCountType` export and ensure it's being implemented properly

2024-04-08 20:34 UTC, bicatcho11 commented
Why is there a huge delay in my withdrawal requests?
There are applications that are immediately accepted or rejected
I hope that the team will process my requests quickly
thank you

2024-04-16 16:08 UTC, Manason commented
What's the purpose of letting police turn on/off the alarm?

2024-04-17 04:51 UTC, bicatcho11 commented
The event already exists
I just completed it
prison:client:JailAlarm

2024-05-02 22:25 UTC, BerkieBb requested changes

2024-05-02 22:25 UTC, BerkieBb commented on server/main.lua
> +    if not exports.qbx_core:GetDutyCountType('leo') then return end
GetDutyCountType does not return a boolean or nil at all, it returns a number representing the amount of people on duty for that type

2024-09-06 15:56 UTC, closed without merging