refactor: refactor config, update readme, manifest
Qbox-project/qbx_prison pull request #37
Opened 2024-04-14 16:51 UTC by KostaZx

## Description

Refactored config, updated readme, manifest.

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-04-15 06:23 UTC, bicatcho11 commented
You have submitted pull requests
I hope to work sequentially from old to new

2024-04-15 06:47 UTC, solareon requested changes
Please address the linting errors and the other comments.

2024-04-15 06:47 UTC, solareon commented on config/shared.lua
> +    useTarget = true, -- Use ox_target interactions (don't change this, go to your server.cfg and add `setr UseTarget true` to use this and just that from true to false or the other way around)
```suggestion
    useTarget = true, -- Use ox_target interactions
```

2024-04-15 06:47 UTC, solareon commented on fxmanifest.lua
> +    'config/shared.lua'
This should be in the files section not as a shared script as we don't need to execute it

2024-04-15 06:47 UTC, solareon commented on client/prisonbreak.lua
I believe that his has not been fully converted.

2024-04-16 16:10 UTC, Manason approved these changes

2024-04-16 16:10 UTC, merged